config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users
  resources :event_attendings, only: [ :create, :destroy ]
  resources :events
  get "up" => "rails/health#show", as: :rails_health_check

  root "events#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :creator, class_name: "User"
  has_many :event_attendings, foreign_key: :event_id
  has_many :attendees, through: :event_attendings, source: :event_attendee
  validates :title, :desc, :date, :location, presence: true

  scope :upcoming, -> { where("date > ?", Time.current) }
  scope :past, -> { where("date < ?", Time.current) }
end

app/models/event_attending.rb
class EventAttending < ApplicationRecord
  belongs_to :event_attendee, class_name: "User"
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :created_events, foreign_key: "creator_id", class_name: "Event", dependent: :destroy
  has_many :event_attendings, foreign_key: "event_attendee_id", class_name: "EventAttending"
  has_many :attended_events, through: :event_attendings, source: :event
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [ :username ])
  end
end

app/controllers/event_attendings_controller.rb
class EventAttendingsController < ApplicationController
  def new
    @attendee = EventAttending.new
  end

  def create
    @attendee = EventAttending.new(event_attending_params)

    if @attendee.save
      redirect_to event_path(@attendee.event_id), notice: "You have successfully registered for the event!"
    else
      redirect_back fallback_location: events_path, alert: "Unable to register for the event"
    end
  end

  def destroy
    event_attending = EventAttending.find(params[:id])
    event = event_attending.event
    event_attending.destroy
    redirect_to event_path(event), notice: "You have deregistered from the event!"
  end

  private

  def event_attending_params
    params.permit(:event_id, :event_attendee_id)
  end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :authenticate_user!, except: [ :index ]
  def index
    @events = Event.all.order(created_at: :desc)
  end

  def new
    @event = Event.new
  end

  def create
    @event = current_user.created_events.build(event_params)

    if @event.save
      redirect_to @event, notice: "Event was succcessfully created."
    else
      flash.now[:error] = "Event creation failed!"
      render :new
    end
  end

  def show
    @event = Event.includes(:attendees).find(params[:id])
  end

  def edit
    @event = Event.find(params[:id])
  end

  def update
    @event = currrent_user.created_events.find(params[:id])
    if @event.update(event_params)
      redirect_to @event, notice: "Event details have been updated!"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @event = current_user.created_events.find(params[:id])
    @event.destroy
    redirect_to events_path, notice: "Event has been successfully deleted"
  end

  private
  def event_params
    params.expect(event: [ :title, :desc, :date, :location ])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, only: [ :show ]
  def show
    @user = User.find(params[:id])
    @events = @user.created_events
    @attends = @user.attended_events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_attendings_helper.rb
module EventAttendingsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/_form.html.erb
<%= form_with model: @event, url: events_path, method: :post do |form| %>
    <% if @event.errors.any? %>
        <div id="error_expalanation">
            <h2><%= pluralize(@event.errors.count, "error")%> prohibited this event from being saved:</h2>
            <ul>
                <% @event.errors.each do |error| %>
                    <li>
                        <%= error.full_message %>
                    </li>
                <% end %>
            </ul>
        </div>
    <% end %>
    
    <div class="field"> 
        <%= form.label :title %>
        <%= form.text_field :title %>
    </div> <br>

    <div class="field">
        <%= form.label :desc %>
        <%= form.text_area :desc %>
    </div> <br>

    <div class="field">
        <%= form.label :location %>
        <%= form.text_field :location %>
    </div><br>

    <div class="field">
        <%= form.label :date %>
        <%= form.datetime_select :date %>
    </div> <br>

    <div class="actions">
        <%= form.submit%>
    </div>
<% end %>

app/views/events/edit.html.erb
<h1>Edit Event</h1>

<%= render "form", event: @event %>
<%= link_to "Cancel", @event %>

app/views/events/index.html.erb
<nav>
    <h1>An Events World</h1>
        <div>
            <% if user_signed_in? %>
                <p>Hi, <strong><%= current_user.username %></strong>!</p>
                <%= link_to 'Your profile', current_user %>&ensp;
                <%= link_to 'Create New Event', new_event_path%>
                <p>
                    <%= button_to 'logout', destroy_user_session_path, method: :delete, class: "btn btn-outline-danger" %><br>
                </p>
            <% else %>
                <p> <%= button_to "Log in", new_user_session_path %></p>
                
                <%= link_to "Sign Up", new_user_registration_path, class: "btn btn-primary" %> 
            <% end %>
    </div>
</nav>

<div>
    <div>
        <h2>Upcoming Events</h1>
    </div>

    <% if @events.any? %>
        <% @events.each do |event| %>
            <h2><%= link_to event.title, event %></h2>
            <span>Created by: <%= event.creator.email %></span>

            <p><%= truncate(event.desc, length: 150) %></p>

            <div>
                <%= link_to 'View Details', event %>
                <% if user_signed_in? && current_user == event.creator %>
                    <%= link_to 'Edit', edit_event_path(event) %>
                <% end %>
            </div>
        <% end %>
    <% else %>
        <div>
            <p>No events found.</p>
            <%= link_to 'Create your first event', new_event_path%>
        </div>
    <% end %>
</div>

app/views/events/new.html.erb
<h1>Create New Event</h1>

<%= render "form", event: @event %>
<%= link_to "Cancel", events_path %>

app/views/events/show.html.erb
<div class="event-details">
    <h1><%= @event.title %></h1>

    <div class="event-meta">
        <p><strong>Brought to you by: </strong> <%=@event.creator.email %></p>
        <p><strong>Date: </strong> <%=@event.date.strftime("%B %d, %Y at %I:%M %p ")%></p>
    </div>

    <div class="event-description">
        <h3>Description</h3>
        <p><%= @event.desc%></p>
    </div>

    <div class="location">
        <h3>location</h3>
        <p><%= @event.location%></p>
    </div>

    <% if current_user != @event.creator && !@event.attendees.include?(current_user) %>
        <%= form_with url: event_attendings_path, method: :post do |f| %>
            <%= hidden_field_tag :event_id, @event.id %>
            <%= hidden_field_tag :event_attendee_id, current_user.id%>
            <%= f.submit "Attend the event" %>
        <% end %>
    <% else %>
        <div>You have registered for the event.</div>
    <% end %>

    <h4>The following users have registered for the event.</h4>
    <p><%= pluralize(@event.attendees.count, "attendee") %></p>

    <% if @event.attendees.any? %>        
        <% @event.attendees.each do |attendee| %>
            <ul>
                <li>
                    <%= link_to attendee.username,attendee %>
                    
                </li>
            </ul>
        <% end %>        
    <% else%>
        <p>No attendees yet!</p>
    <% end %>


    <% if current_user == @event.creator %>
        <div class="event-action">
            <div><%= link_to 'Edit Event', edit_event_path(@event), class: 'btn btn-primary' %></div> <br>
            <%= button_to 'Delete Event', @event, method: :delete, data: { confirm: 'Are you sure?' } %>
        </div>
    <% end %><br>

    <div>
        <% event_attending = EventAttending.find_by(event_id: @event.id, event_attendee_id: current_user.id) %>
        <% if event_attending %>
            <%= button_to "Deregister", event_attending_path(event_attending), method: :delete, data: { confirm: 'Are you sure?' } %>
        <% end %>
    </div><br>

    <%= link_to 'Back to Events', events_path, class: 'btn btn-secondary'%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Private Events" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%#= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <% flash.each do |key, value| %>
      <div class="alert alert" <%= key %>> <%= value %></div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/users/show.html.erb
<h1>User Profile </h1>
<p>Hi, <%= @user.username %> </p>

<h2>Events you have created!</h2>
<ul>
    <% if @events.any? %>
        <% @events.each do |event| %>
            <li>
                <%= link_to event.title, event %>
                <% event.created_at.to_formatted_s(:long) %>
            </li>
        <% end %>
    <% else %>
        <p>@<%= @user.username %> hasn't created any events yet.</p>
    <% end %>
</ul>


<h2>Event Registrations!</h2>
<% upcoming_events = @attends.select { |event| event.date.future? } %>
<% past_events = @attends.select { |event| event.date.past? } %>

<% if upcoming_events.any? %>
    <h3>Upcoming events</h3>
    <ul>
        <% upcoming_events.each do |event| %>
            <li>
                <%= link_to event.title, event %>
                <%= event.date.to_formatted_s(:long) %>
            </li><br>
        <% end %>
    </ul>
<% end %>

<% if past_events.any? %>
    <h3>Past events</h3>
    <ul>
        <% past_events.each do |event| %>
            <li>
                <%= link_to event.title, event %>
                <%= event.date.to_formatted_s(:long) %>
            </li><br>
        <% end %>
    </ul>
<% end %>

<% if upcoming_events.empty? && past_events.empty? %>
    <p>@<%= @user.username%> hasn't attended any events yet!</p>
<% end %>